name: Migrate Sanity Assets
on: workflow_dispatch
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/DromedaDev/serpent-tongue-assets.git
          node scripts/prepare-github-assets.js
          git add .
          git commit -m "chore: migrate assets"
          git push origin main
