name: Migrate Sanity Assets to GitHub
on:
  workflow_dispatch:
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Download and Upload Assets
        run: |
          mkdir -p assets
          node scripts/prepare-github-assets.js
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "chore: bulk migrate assets to storage"
          git push
